### ISSUE TITLE
Could you please offer a more detailed explanation for the parameters?

### ISSUE THREAD

**Issue by beckhamwjc** [SimonBlanke/optimization-tutorial#1]
I am a newbie to the optimization methods and I'm really confused with the "default Parameters" for every optimization algorithm and the "Optimizer Parameters". 

I was working with the ParticleSwarmOptimizer, and I changed the "population" from 10 to 11, resulting the warning "Not enough initial positions for population size. Population size is reduced to 10." I have tried to change other parameters but failed to get the "population" larger than 10.

Could you please offer a little more detailed explanation for these parameters on the possible range of them and how they will affect the optimization results when twicking them? Perhaps something similar as the XGBoost docs (https://xgboost.readthedocs.io/en/stable/parameter.html)?

Thanks!

**Comment by SimonBlanke** [comment]
Hello @beckhamwjc,

A larger population size needs more initial positions. This can be achieved by adding more positions to the `initialize`-parameter. You could just increase the random initialized positions.

I am currently working on a more detailed version of the optimization tutorial with additional plots and explanations. The readme in this repository is just a very basic version.

**Comment by SimonBlanke** [comment]
Hello @beckhamwjc,

If you want more information about the optimization algorithms and their parameters there is a streamlit-based page in this repository. You can access it from the readme for now, but as discussed in https://github.com/SimonBlanke/optimization-tutorial/issues/4 I will create a separate documentation page that will contain API information about all optimizers and their paramters.
