### ISSUE TITLE
High-level documentation

### ISSUE THREAD

**Issue by jordannickerson** [SimonBlanke/optimization-tutorial#5]
I've been going through the documentation, and am rather confused about the basic parameters used across the different algorithms (and the HillClimbingOptimizer algo in particular). Specifically I'm referring to the 'search_space' parameter, and its expected structure. The docs describe search_space as the space where the algo can search, but the example is an array with evenly spaced points. In HillClimbingOptimizer, candidates are drawn from a normal distribution around the current point, so it isn't clear why we pass a discrete grid of many points to the optimizer to define the search space. Does it only draw points from these values?

For clarity, I'd suggest following a similar documentation structure as Scipy, which lays out the expected dimensions, values, characteristics, etc. of each parameter used.

**Comment by SimonBlanke** [comment]
Hello @jordannickerson,

The `search_space`-parameter must be a dictionary, where the keys are the names of the dimensions (that can be accessed in the objective-function) and the values are the arrays (or evenly spaced points). 

> Does it only draw points from these values?

Correct! :-) The hill climbing optimizer has a current position in the search-space which is the center point of the normal-dist. The parameter `epsilon` is a factor for the standard-deviation and set to a value that corresponds to a local search algorithm.

I hope I was able to help you with this explanation! 

Writing a detailed documentation of all these optimization algorithms is a current project of mine (and is a bigger challenge than I thought). I am not satisfied with the streamlit-page in this repository as described in issue SimonBlanke/optimization-tutorial#4, but I am open to suggestions. Do you have a link to the scipy-doc?

**Comment by jordannickerson** [comment]
understood, thanks!

Here is a link to one of Scipy's optimization packages: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize_scalar.html#scipy.optimize.minimize_scalar

What is nice about the documentation is that it lays out the exact argument types expected, along with examples, leaving very little to be interpreted.

**Comment by SimonBlanke** [comment]
Hello @jordannickerson,

Over the last 10 days I wrote the [gradient-free-optimization-documentation](https://simonblanke.github.io/gradient-free-optimizers-documentation/1.0/). Please let me know if this is helpful.

I really like this solution so far. Mkdocs has some nice features, but it is also very simple and easy to use.

If there is stuff to improve you can open issues in the corresponding [repository](https://github.com/SimonBlanke/gradient-free-optimizers-documentation).
